### ISSUE TITLE
Using not all tools results in error

### ISSUE THREAD

**Issue by VGalata** [linnabrown/run_dbcan#28]
Hi,

I tried to run `dbCAN2` on a FASTA file containing proteins from a metagenomic assembly. Since I have many samples and the analysis takes some time, I wanted to use only one tool, namely `hmmer`. Here is how I call `dbCAN2`:
```bash
 run_dbcan.py sample.faa protein --out_dir output/ --out_pre "sample." --db_dir path/to/dbcan2 -t hmmer --hmm_cpu 6 --dia_cpu 6 --tf_cpu 6 --stp_cpu 6
```

After the HMM-search is finished I get the following error:
```
Traceback (most recent call last):
  File "/mypath/.snakemake/conda/a2cab093/bin/run_dbcan.py", line 581, in <module>
    if(arr_diamond != None):
NameError: name 'arr_diamond' is not defined
```

The problem is that you do not define the variable `arr_diamond` etc. if there is no output file for the corresponding tool (starting from [here](https://github.com/linnabrown/run_dbcan/blob/master/run_dbcan.py#L538)). Adding an `else` statement and setting these variables to `None` has solved my issue and the tool is able to complete the job.

Used `conda` config:
```yaml
channels:
    - conda-forge
    - bioconda
dependencies:
    - pip
    - diamond==0.9.28
    - hmmer==3.1b2
    - pip:
        - run-dbcan==2.0.1
```
